### ISSUE TITLE
Creation of edf files with custom names/at custom locations for eyelink

### ISSUE THREAD

**Issue by ClementAbb** [Intrepid-2a/EyeTracking#11]
Log when trying to create file:

```
ERROR: DEVICE CONFIG ERRORS FOUND! IOHUB NOT LOADING DEVICE: psychopy.iohub.devices.eyetracker.hw.sr_research.eyelink
errors count 1:
        ('default_native_data_file_name', 'test_dist_LH_1')


not_found count 1:
        ('local_edf_dir', '../data/distance/eyetracking/test/')


## Device was not started by the ioHub Server: eyetracker.hw.sr_research.eyelink.EyeTracker
Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)

Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 642, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf) 
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 721, in createNewMonitoredDevice
    raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)

GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
```

**Comment by thartbm** [comment]
First bit of this is related to directories for edf file creation, but most has to do with window objects (separate issue).

In my version of the experiment, we had these lines:

```
eyetracking_path = main_path + 'eyetracking/' + ID + '/'

os.makedirs(eyetracking_path, exist_ok=True)
```

With a few lines in between. This ensures that the folder for the participants' data exists, before creating the eye-tracker object.

**Comment by ClementAbb** [comment]
The folder does exist.

**Comment by ClementAbb** [comment]
Could it be something silly like eyelink not being able to handle relative paths?

**Comment by thartbm** [comment]
Something like this, to get the absolute path to the directory above the one where the experiment runs:

```
In [4]: os.getcwd()
Out[4]: '/home/marius'

In [5]: os.path.split(os.getcwd())
Out[5]: ('/home', 'marius')

In [6]: [head, tail] = os.path.split(os.getcwd())

In [7]: head
Out[7]: '/home'
```

And then something like this to account for operating system specifics in path names:

```
In [9]: os.path.join(head, 'data','distance','eyetracking','participant007')
Out[9]: '/home/data/distance/eyetracking/participant007'
```

(Of course replacing 'distance' with other experiment names, as needed, and 'participant007' with whatever ID the current participant has.)

**Comment by thartbm** [comment]
Errr... maybe not fully clear. You only need lines In[6] and In[9] I guess, and expand a little so it fits into our structure:

```
[head, tail] = os.path.split(os.getcwd())
data_path = os.path.join(head, 'data', 'distance')
eyetracking_path = os.path.join(data_path, 'eyetracking', ID)
```

**Comment by ClementAbb** [comment]
I get the impression that what you are working on for finding/deleting/moving the default edf files will also solve this, so I will hang on for now on this.

**Comment by thartbm** [comment]
Hmmm. Could be, but I thought these were separate issue, with different symptoms? I.e. when specifying file & folder it doesn't work at all (this issue) and when not specifying them you still get the default output file cluttering up a folder that should only have code in it (other issue).

It makes sense to me not to solve this current issue in the eye-tracker object: it seems to me that it should receive a correct (existing, useable, ...) folder & file name. The above code is one way (very generic, should work on any machine) to solve the current issue, from within some other point in the code.

**Comment by ClementAbb** [comment]
Absolute paths don't solve the issue:

```
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
{'both': [1, 1, 1], 'back': [0.55, 0.45, -1.0]}
{'both': [1, 1, 1], 'back': [0.55, 0.45, -1.0]}
C:\Users\clementa\Desktop\templeton_gh\data\distance\eyetracking\test
test_dist_LH_1
True
ERROR: DEVICE CONFIG ERRORS FOUND! IOHUB NOT LOADING DEVICE: psychopy.iohub.devices.eyetracker.hw.sr_research.eyelink
errors count 1:
        ('default_native_data_file_name', 'test_dist_LH_1')


not_found count 1:
        ('local_edf_dir', 'C:\\Users\\clementa\\Desktop\\templeton_gh\\data\\distance\\eyetracking\\test')


## Device was not started by the ioHub Server: eyetracker.hw.sr_research.eyelink.EyeTracker
Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)

Error during device creation ....
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 716, in createNewMonitoredDevice
    raise ioHubError('Device config validation failed')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Device config validation failed',)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 642, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf)
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\server.py", line 721, in createNewMonitoredDevice
    raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)

GET_DEV_INTERFACE_ERROR: _getRPCInterface returned: None
Exception ignored in: <function EyeTracker.__del__ at 0x0000026B55FAFCA0>
Traceback (most recent call last):
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1300, in __del__
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1277, in __EL_shutdown
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1007, in __EL_stopcollecting
  File "C:\Program Files\PsychoPy_2022\lib\site-packages\psychopy\iohub\client\__init__.py", line 153, in __getattr__
AttributeError: (<psychopy.iohub.client.ioHubDeviceView object at 0x0000026B63E63AF0>, 'setRecordingState')
PS C:\Users\clementa\Desktop\templeton_gh\Distance> 0.6933      WARNING         Monitor specification not found. Creating a temporary one...
```

**Comment by thartbm** [comment]
I'm starting to think that by "local" they mean "on the EyeLink PC", not the PC on which the experiment is running. Such that perhaps the default file name, and the path, are not to be touched (giving a filename is an error?).

One strategy to deal with this, is to *never* specify them in the IoHub dictionary. The file will always download to "[working directory]/et_data.edf". But then we do add some lines to one of the closing functions to rename it and move it to where we want. This can only be done after the file is downloaded, and iirc this happens when the link to the eye-tracker or the whole iohub thing are closed. So that would be in the shutdown function - which is a bit precarious, but it's worth a shot. 

What do you think?

There is a risk. Using the default name all the time, probably means that you will only have the latest recording stored on the EyeLink, because they would overwrite each other (even within a participant). In case of disaster that means there is no back-up on the EyeLink PC. So if you like we could pursue something else.

Perhaps the filename needs to conform to DOS filename rules. They can only have 8 characters for the main name (broke that), and 3 characters for the extension (we can't even specify it, so not relevant). There's no distinction between upper and lower case letters and there are also some forbidden characters, but I forgot which, and don't think we're using weird ones anyway. Similarly, foldernames can only have 8 characters, and there are two in the full path there that have more.

So we could use these folders:
AREA, CURVE, DIST

And then have filenames with two characters specifying task and hemishpere (e.g. area task, left hemisphere: "AL") and have 6 characters to specify the participant, and maybe location (e.g. Glasgow, participant 123: "GL0123").

In the end you'd get filenames on the EyeLink like: "AREA/ALGL0123.EDF" and you could use the Windows boot option to rescue files manually and at least know what is what by virtue of those minimalistic folder- and filenames.

One test to see if this works would be to make some kind of folder on the EyeLink, relative to where the software stores its files by default, I guess, with some useful name. Then set the folder argument to that (and empty folder string may give unexpected results and None will stop file/folder downloading). The filename could be something like "TEST1234". Then see if something gets downloaded with such a name, and also see if there is a file called TEST1234.EDF on the EyeLink PC. If so, it might be worth changing the file naming scheme.

But if you feel like it's a waste of time, we can go for the other option.

**Comment by ClementAbb** [comment]
> I'm starting to think that by "local" they mean "on the EyeLink PC", not the PC on which the experiment is running. Such that perhaps the default file name, and the path, are not to be touched (giving a filename is an error?).

Possible.

> One strategy to deal with this, is to never specify them in the IoHub dictionary. The file will always download to "[working directory]/et_data.edf". But then we do add some lines to one of the closing functions to rename it and move it to where we want. This can only be done after the file is downloaded, and iirc this happens when the link to the eye-tracker or the whole iohub thing are closed. So that would be in the shutdown function - which is a bit precarious, but it's worth a shot.

Yes this is what I was suggesting in the other issue. Happy to go with that. We might not get the full data (or not at the right name or in the right position) if the experiment just crashes. At that point the dataset overall will be sketchy/incomplete so I would say it's worth it.

**Comment by thartbm** [comment]
OK, I added some lines to the shutdown function. I'm assuming that the standard file will _always_ be called `et_data.EDF` and then move that file to what I think is the right location and filename.

What do you think happens if that file already exists when you start an experiment? If that creates something like `et_data(2).EDF` we'd also have to check for the standard file at the start of any run.

Just thought that in case of blind spot mapping or any other situation where `self.storefiles == False`, we might want to think about deleting the default file, or moving it to some back up folder.

**Comment by thartbm** [comment]
Considering this closed. Only leaving the other issue open for now.
