### ISSUE TITLE
custom fixation for waitForFixation()

### ISSUE THREAD

**Issue by ClementAbb** [Intrepid-2a/EyeTracking#16]
I'm testing waitForFixation and it works fine, except that it would be nice to have an argument specifying what is displayed at the center of the screen (right now it's one of the targets from calibration).

Ideally it would work like:

`good_fixation = tracker.waitForFixation(fixation = fixation)`

Where 'fixation' is the psychopy object I use as a fixation throughout the experiment.

**Comment by ClementAbb** [comment]
Also do we not want to have fusion stimuli displayed during this time?

**Comment by thartbm** [comment]
Not sure, I see this as pre-trial and eye-tracking related, so I used the calibration target stimulus that exists in the eye-tracker object (need it for LiveTrack) and the fixation target should be visible to both eye anyway, so fusion stimuli are not strictly necessary.

But it's all possible. However, rather than sending the fixation object to the eye-tracker object for every fixation trial, it makes a little more sense to do this when creating the object, so it just stays there, and the amount of stuff going back and forth is minimized a bit. If it doesn't get sent on initialization, the current thing gets used. And if we want, we can still add something to send a different object for the odd fixation check where we want to do something different after all.

**Comment by ClementAbb** [comment]
Ok, I'm fine with that for the fixation and I have no strong opinion on the fusion stims.

**Comment by thartbm** [comment]
The advantage of keeping it all on the screen in the same form is that there is less change on the screen to distract the participant. It may help them maintain fixation. So I guess having some options for that would not be wrong. I'll just have think of a way to do it that would also work for other projects.

**Comment by thartbm** [comment]
Implemented basic things:
- argument `fixationTarget` in init function to take a fixation object, which is passed to:
- method `setFixationTarget()` that checks 2 properties of the passed fixationTarget object before setting it as a property of the eyetracker object:
    1. it has the draw method, likely making it a psychopy stimulus
    2. it is defined for the same psychopy window used by the `waitForFixation()` method
- argument in `waitForFixation()` method to override default

The method `setFixationTarget()` can also be called later to change the fixation target. And probably the property `fixationTarget` can also be set directly after the object is initialized.

Let me know if this works?

**Comment by ClementAbb** [comment]
Doesn't seem to work quite yet.
I tested:

```
win = visual.Window([1500,800],allowGUI=True, monitor='ExpMon',screen=1, units='deg', viewPos = [0,0], fullscr = True, color= col_back)
fixation_yes = visual.ShapeStim(win, vertices = ((0, -2), (0, 2), (0,0), (-2, 0), (2, 0)), lineWidth = 2, units = 'pix', size = (10, 10), closeShape = False, lineColor = col_both)

[...]

tracker.setFixationTarget(fixation_yes)
```

Got

```
PS C:\Users\clementa\Desktop\templeton_gh\Distance> & "C:\Program Files\PsychoPy_2022\python.exe" .\ET_for_glasgow_test.py
pygame 2.1.0 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File ".\ET_for_glasgow_test.py", line 54, in <module>
    tracker = EyeTracker(tracker           = 'eyelink',
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 71, in __init__
    self.setFixationTarget(fixationTarget)
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 258, in setFixationTarget
    raise Warning("fixationTarget must be a PsychoPy visual stimulus with the draw method")
Warning: fixationTarget must be a PsychoPy visual stimulus with the draw method
```

**Comment by ClementAbb** [comment]
Same when trying `good_fixation = tracker.waitForFixation(fixationTarget = fixation_yes)`

**Comment by ClementAbb** [comment]
Same when... not specifying a fixation?

**Comment by ClementAbb** [comment]
Ok I got that one, it's because of the default value of None.

This doesn't happen with:

```
tracker = EyeTracker(tracker           = 'eyelink',
                     trackEyes         = [True, True],
                     fixationWindow    = 2.0,
                     minFixDur         = 0.2,
                     fixTimeout        = 3.0,
                     psychopyWindow    = win,
                     filefolder        = eyetracking_path,
                     filename          = et_filename+str(y),
                     samplemode        = 'average',
                     calibrationpoints = 5,
                     colors            = colors,
                     fixationTarget    = fixation_yes) 
```

However the attribute check still crashes:

```
Traceback (most recent call last):
  File ".\ET_for_glasgow_test.py", line 87, in <module>
    good_fixation = tracker.waitForFixation()
  File "C:\Users\clementa\Desktop\templeton_gh\Distance\..\EyeTracking\EyeTracking.py", line 1226, in waitForFixation
    if hasattr(self, fixationTarget):
TypeError: hasattr(): attribute name must be string
```

**Comment by ClementAbb** [comment]
I managed to make it work by:
- specifying the fixation target when creating the object to bypass the faulty check
- commenting out the attribute check of waitForFixation
 ```
 '''
        if fixationTarget == None:
            if hasattr(self, fixationTarget):
                fixation = self.fixationTarget
            else:
                fixation = self.target
        else:
            # not checking if this is a correct object, leaving to caller:
            fixation = fixationTarget
        '''
        fixation = fixationTarget
```
- still specifying the target in the call for waitForFixation: `good_fixation = tracker.waitForFixation(fixationTarget = fixation_yes)`

**Comment by ClementAbb** [comment]
> The advantage of keeping it all on the screen in the same form is that there is less change on the screen to distract the participant. It may help them maintain fixation. So I guess having some options for that would not be wrong. I'll just have think of a way to do it that would also work for other projects.

One way I can think of is instead of passing a fixation argument, you pass a 'to_draw' list of objects that should be drawn during fixation. The default list being only the default fixation target.

**Comment by thartbm** [comment]
I came up with more or less the same thing, let's see if we can get that working. But first solve the errors here. 

I made the same error in the `hasattr` as I did in some previous uses... so that should be fixed.

Don't know what's happening in the setFixationtarget function though, so I've just added some print debugging lines to the function. The ideas are that whatever you throw in there should be a psychopy stimulus that is associated with the `psychopyWindow` that is also provided. There are many different types of stimuli though, so it's a bit of an indirect check. Here's how I expected that to happen:

```
In [6]: from psychopy import visual
pygame 2.2.0 (SDL 2.0.22, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html

In [7]: win = visual.Window([750, 750])

In [8]: target = visual.TargetStim(win,
   ...:                                         name='fixTarget',
   ...:                                         radius=0.5,
   ...:                                         innerRadius=0.1,
   ...:                                         fillColor=[-1,-1,-1],
   ...:                                         innerFillColor=[1,1,1],
   ...:                                         lineWidth=0,
   ...:                                         innerLineWidth=0,
   ...:                                         borderColor=None,
   ...:                                         innerBorderColor=None,
   ...:                                         units='deg')

In [9]: hasattr(target, 'draw')
Out[9]: True

In [10]: callable(target.draw)
Out[10]: True

In [11]: target.win == win
Out[11]: True

In [12]: 
```

Made a window and a stimulus. The stimulus has an attribute called 'draw'. That attribute is callable. And the stimulus is defined for the correct window. Not so, I guess?

**Comment by thartbm** [comment]
For later: my guess is that if we pass a list of things for display during wait-for-fixation, they end up being pointers, not copies. So that would mean that if we put the fusion stimuli in there when generating the eye-tracker object (instead of during each call to the waitForFixation function) we can still update the random pattern right before the call to the waitForFixation function and it should be displayed with the new pattern.

But we should try this after this stuff is fixed. The checks above are done at initialization, and they are meant to ensure that the input is of the expected kind (like all of those function do) such that things will run smoothly during the experiment. The checks seem not to work in the object though, and I have no idea why.

**Comment by ClementAbb** [comment]
With the code right now it seems to work properly (either specifying the fixation when creating the object or when calling waitForFixation).

**Comment by ClementAbb** [comment]
Yes that works.
